version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch_legalbot
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    networks:
      - elastic_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

  scripts:
    build:
      context: .
      dockerfile: Dockerfile.scripts
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
      - ./config.py:/app/config.py
    depends_on:
      - elasticsearch
    entrypoint: ["bash"]
    networks:
      - elastic_network

networks:
  elastic_network:
    driver: bridge

volumes:
  elasticsearch_data: